### ISSUE TITLE
Multi file xml 

### ISSUE THREAD

**Issue by SiNguyen0604** [yeniel/native_shared_preferences#3]
Hi @yeniel @cznico 
Current native_shared_preferences only read a flie xml
<resources>
    ...
    <string name="flutter_shared_pref_name">resource_name</string>
    ...
</resources>

I want to read many sharePreference from xml files native app android. who can help me .

**Comment by flutter-clutter** [comment]
Not possible currently, since the file name is given in string resource xml file, which is read once during compile time. This is a huge flaw in my opinion because it's very common to spread the local data across multiple xml files.
