### ISSUE TITLE
Support setString('key', null), setInt('key', null) etc

### ISSUE THREAD

**Issue by TheoLassonder** [yeniel/native_shared_preferences#7]
It's just so convenient to be able to set a string to null to mean "remove the value". It's also what `shared_preferences` package does.

Instead of code like:

```
if (from == null) {
  await prefs.remove('epochFrom');
} else {
  await prefs.setInt('epochFrom', from.millisecondsSinceEpoch);
}
```

you can write:

`await prefs.setInt('epochFrom', from?.millisecondsSinceEpoch);`

Best of all, this feature can be added with backwards compatibility.

**Comment by myselfuser1** [comment]
This might help https://www.youtube.com/watch?v=WN3g1YZswrA

**Comment by yeniel** [comment]
Hi!
This feature is already supported. I will update the example adding a Reset button to the counter. 
Thanks! 🙂
